<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ClientSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('clients')->insert([
            [
                'full_name' => 'María López',
                'dni' => 40123456,
                'phone' => '1167891234',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Carlos Pérez',
                'dni' => 39234567,
                'phone' => '1134567890',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Laura Fernández',
                'dni' => 42123456,
                'phone' => '1123456789',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Diego Ramírez',
                'dni' => 38543210,
                'phone' => '1145678912',
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Sofía Gómez',
                'dni' => 41456789,
                'phone' => '1176543210',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Julián Martínez',
                'dni' => 39765432,
                'phone' => '1156782345',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Valentina Rodríguez',
                'dni' => 43567890,
                'phone' => '1165437890',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Martín González',
                'dni' => 37890123,
                'phone' => '1143215678',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Camila Torres',
                'dni' => 42987654,
                'phone' => '1178901234',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Nicolás Silva',
                'dni' => 40198765,
                'phone' => '1134567891',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lucía Castro',
                'dni' => 44765432,
                'phone' => '1167894561',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Federico Morales',
                'dni' => 38654321,
                'phone' => '1145671234',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Agustina Romero',
                'dni' => 41876543,
                'phone' => '1156789012',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Tomás Herrera',
                'dni' => 39543218,
                'phone' => '1132109876',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Florencia Molina',
                'dni' => 42345678,
                'phone' => '1176540987',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Sebastián Ortiz',
                'dni' => 38123457,
                'phone' => '1143218901',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Carolina Núñez',
                'dni' => 43678901,
                'phone' => '1165432109',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Lucas Acosta',
                'dni' => 40765431,
                'phone' => '1154321098',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Micaela Ríos',
                'dni' => 44567812,
                'phone' => '1178904567',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Gabriel Medina',
                'dni' => 37456789,
                'phone' => '1134560123',
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Paula Cabrera',
                'dni' => 41678923,
                'phone' => '1167890123',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Andrés Vargas',
                'dni' => 38901234,
                'phone' => '1145678902',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Daniela Suárez',
                'dni' => 43123489,
                'phone' => '1156783456',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Ignacio Pereyra',
                'dni' => 39876541,
                'phone' => '1132106543',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Julieta Benítez',
                'dni' => 42789012,
                'phone' => '1176543219',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Matías Figueroa',
                'dni' => 38234519,
                'phone' => '1145672345',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Rocío Domínguez',
                'dni' => 43987621,
                'phone' => '1167893456',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Emiliano Sosa',
                'dni' => 40345671,
                'phone' => '1154326789',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Natalia Correa',
                'dni' => 41567834,
                'phone' => '1178906789',
                'status' => 'inactive',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'full_name' => 'Pablo Arias',
                'dni' => 39123485,
                'phone' => '1134563456',
                'status' => 'active',
                'created_at' => now(),
                'updated_at' => now(),
            ],
        ]);
    }
}